### ISSUE TITLE
make rpm failed with 404 for storm

### ISSUE THREAD

**Issue by huiyiqun** [WEZARD/pangu_ansible#1]
既然storm-0.9.2发布的文件名是`apache-storm-0.9.2-incubating.tar.gz`，为什么在SPEC文件里要写：

```
Source: http://mirrors.sonic.net/apache/storm/apache-storm-0.9.2-incubating/storm-0.9.2.tar.gz
```

这样`make rpm`的过程中，spectool会尝试去上面的地址下载发布的文件，这时会404失败。

另外关于makefile的写法，建议你看一下[这个](http://mrbook.org/blog/tutorials/make/)

> The basic makefile is composed of:
> 
> `target: dependencies`
> `[tab] system command`

在你的makefile里面用的是空格而不是tab，这样make执行会失败，麻烦修改一下。

**Comment by WEZARD** [comment]
这个问题已经解决。我是更换了一个更新的版本

```
Source: http://apache.mirrors.hoobly.com/storm/apache-storm-0.9.4/apache-storm-0.9.4.tar.gz
```

因为我不知道原来那个版本号后的  -incubating，怎么加到 rpm 的名字中。

makefile 由于我是复制过去的，导致 tab 符号那里出了问题。
