### ISSUE TITLE
Error in storm.spec

### ISSUE THREAD

**Issue by huiyiqun** [WEZARD/pangu_ansible#5]
https://github.com/WEZARD/pangu_ansible/blob/67ad077268b28029e4c1dccbb79f57bc2fc77562/roles/pangu-storm/files/storm.spec#L35

你把文件放到**编译机器**的`/opt`干嘛。。

**Comment by huiyiqun** [comment]
我差点以为你要删了我的根目录

**Comment by WEZARD** [comment]
这个是安装 rpm 包的时候将文件放到目标机器的 /opt 目录下

**Comment by WEZARD** [comment]
那个地方不小心改错了，已经更正过来
